package org.openqa.selenium.amazon.merch.auto;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.openqa.selenium.WebDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

import static org.openqa.selenium.amazon.merch.auto.AmazonTool.*;

public class MerchForm {
	public static final String INI_CHROME_DIR = "chrome-dir";
	public static final String INI_DATA_DIR = "data-dir";
	public static final String INI_PW = "pw";
	private static final Logger LOG = LoggerFactory.getLogger(MerchForm.class);
	private static final File iniFile = new File(USER_HOME, ".ezmerch.ini");
	private final DefaultListModel<File> selectedDataFiles = new DefaultListModel<>();
	private final JFileChooser dataChooser = new JFileChooser();
	private JPanel panelMain;
	private JTextField chromeDirTextField;
	private JButton chooseButton;
	private JButton initiateButton;
	private JPasswordField passwordField;
	private JList<File> productList;
	private JButton browseDataButton;
	private JButton checkButton;
	private JButton submitButton;
	private JButton deleteButton;
	private volatile List<Product> products = null;
	private volatile WebDriver webDriver = null;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	private MerchForm() {
		initiateButton.addActionListener(event -> {
			int i = JOptionPane.showConfirmDialog(panelMain, "Chrome will be opened. Please log-in to your merch account and then quit Chrome");
			if (i == JOptionPane.OK_OPTION) {
				if (hasQuit(webDriver)) {
					webDriver = AmazonTool.getWebDriver(chromeDirTextField.getText());
				}
				webDriver.get("https://merch.amazon.com/dashboard");
				waitForDriverToClose(webDriver);
			}
		});
		chooseButton.addActionListener(actionEvent -> {
			JFileChooser chooser = new JFileChooser();
			chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
			chooser.setAcceptAllFileFilterUsed(false);
			if (chooser.showOpenDialog(chooseButton) == JFileChooser.APPROVE_OPTION) {
				File folder = chooser.getSelectedFile();
				chromeDirTextField.setText(folder.toString());
			}
		});
		dataChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		dataChooser.setMultiSelectionEnabled(true);
		dataChooser.setAcceptAllFileFilterUsed(true);
		browseDataButton.addActionListener(actionEvent -> {
			if (dataChooser.showOpenDialog(browseDataButton) == JFileChooser.APPROVE_OPTION) {
				File[] files = dataChooser.getSelectedFiles();
				for (File file : files) {
					if (!selectedDataFiles.contains(file)) {
						selectedDataFiles.addElement(file);
					}
				}

			}
		});
		productList.setModel(selectedDataFiles);
		productList.addKeyListener(new KeyListener() {
			@Override
			public void keyTyped(KeyEvent keyEvent) {

			}

			@Override
			public void keyPressed(KeyEvent keyEvent) {
				if (keyEvent.getKeyCode() == KeyEvent.VK_DELETE) {
					for (File file : productList.getSelectedValuesList()) {
						selectedDataFiles.removeElement(file);
					}
				}
			}

			@Override
			public void keyReleased(KeyEvent keyEvent) {

			}
		});
		checkButton.addActionListener(event -> {
			int n = selectedDataFiles.getSize();
			products = new ArrayList<>();
			for (int i = 0; i < n; i++) {
				try {
					productList.setSelectedIndex(i);
					Product product = Product.parseFromJson(selectedDataFiles.get(i));
					products.add(product);
				} catch (Exception e) {
					JOptionPane.showMessageDialog(panelMain, "Error when parsing file " + selectedDataFiles.get(i) + ". Error:\n" + e.toString());
					LOG.error("Error when parsing file {}", selectedDataFiles.get(i), e);
					products = null;
					break;
				}
			}
			if (products != null) {
				JOptionPane.showMessageDialog(panelMain, "Loaded " + products.size() + " product(s)");
			}
		});
		submitButton.addActionListener(actionEvent -> {
			if (products == null) {
				JOptionPane.showMessageDialog(panelMain, "Please \"check\" the data files first");
			} else if (products.size() == 0) {
				JOptionPane.showMessageDialog(panelMain, "There is no product to summit");
			} else {
				int confirmResult = JOptionPane.showConfirmDialog(panelMain, "We are submitting " + products.size() + " product. Please confirm to process...");
				if (confirmResult == JOptionPane.OK_OPTION) {
					if (hasQuit(webDriver)) {
						webDriver = AmazonTool.getWebDriver(chromeDirTextField.getText());
					}
					try {
						for (Product product : products) {
							Auto.createNewProduct(webDriver, product, new String(passwordField.getPassword()));
						}
						JOptionPane.showMessageDialog(panelMain, "Done!");
					} catch (Exception e) {
						LOG.error("Error when submitting", e);
						JOptionPane.showMessageDialog(panelMain, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
					} finally {
						products = null;
					}
				}
			}
		});
		deleteButton.addActionListener(e -> {
			for (File file : productList.getSelectedValuesList()) {
				selectedDataFiles.removeElement(file);
			}
		});
		chromeDirTextField.setText(USER_HOME.toPath().resolve("chrome-amazon").toString());
	}

	public static void main(String[] args) throws IOException {
		MerchForm form = new MerchForm();
		if (iniFile.exists() && iniFile.isFile()) {
			List<String> strings = Files.readAllLines(iniFile.toPath());
			for (String string : strings) {
				int index = string.indexOf('=');
				if (index < 0) {
					continue;
				}
				String attribute = string.substring(0, index);
				String data = string.substring(index + 1);
				if (INI_CHROME_DIR.equals(attribute)) {
					form.chromeDirTextField.setText(data);
				} else if (INI_DATA_DIR.equals(attribute)) {
					if (new File(data).isDirectory()) {
						form.dataChooser.setCurrentDirectory(new File(data));
					}
				} else if (INI_PW.equals(attribute)) {
					form.passwordField.setText(data);
				}
			}
		}
		JFrame frame = new JFrame("EZMerch Tool");
		frame.setContentPane(form.panelMain);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				try (BufferedWriter writer = new BufferedWriter(new FileWriter(iniFile))) {
					writer.write(INI_CHROME_DIR + "=" + form.chromeDirTextField.getText() + "\n");
					writer.write(INI_DATA_DIR + "=" + form.dataChooser.getCurrentDirectory() + "\n");
					writer.write(INI_PW + "=" + new String(form.passwordField.getPassword()) + "\n");
				} catch (IOException ex) {
					LOG.error("Exception when saving ini file", ex);
				}
				try {
					Process p = Runtime.getRuntime().exec("attrib +h " + iniFile.getAbsolutePath());
					p.waitFor();
				} catch (Exception ex) {
					LOG.error("Exception when hide the ini file", ex);
				}
				super.windowClosing(e);
			}
		});
		frame.pack();
		frame.setVisible(true);
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panelMain = new JPanel();
		panelMain.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panelMain.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		panel1.setBorder(BorderFactory.createTitledBorder("Amazon's account password"));
		passwordField = new JPasswordField();
		panel1.add(passwordField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
		panelMain.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		panel2.setBorder(BorderFactory.createTitledBorder("Chrome's user dir"));
		chromeDirTextField = new JTextField();
		panel2.add(chromeDirTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(350, -1), null, 0, false));
		chooseButton = new JButton();
		chooseButton.setText("Choose");
		panel2.add(chooseButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		initiateButton = new JButton();
		initiateButton.setText("Initiate");
		panel2.add(initiateButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
		panelMain.add(panel3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		panel3.setBorder(BorderFactory.createTitledBorder("Data "));
		productList = new JList();
		productList.setVisibleRowCount(12);
		panel3.add(productList, new GridConstraints(0, 0, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(750, 500), null, 0, false));
		browseDataButton = new JButton();
		browseDataButton.setText("Browse");
		panel3.add(browseDataButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		checkButton = new JButton();
		checkButton.setText("Check");
		panel3.add(checkButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		submitButton = new JButton();
		submitButton.setText("Submit");
		panel3.add(submitButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		deleteButton = new JButton();
		deleteButton.setText("Delete");
		panel3.add(deleteButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panelMain;
	}

}
